#!/bin/bash
#PBS -l nodes=1:ppn=1:gpus=1:k80,mem=10GB
#PBS -l walltime=2:00:00
#PBS -N PBS_runTheanoMPI_1GPU
#PBS -M lt1410@nyu.edu
#PBS -j oe

module purge
module load theano
module load mpi4py
pip install --user pyzmq
pip install --user hickle
module unload numpy
module load pycuda
module load cudnn
module load cuda


RUNDIR=$SCRATCH/MultiGPU/Theano-MPI/run/
cd $RUNDIR

bash run_bsp_workers.sh 1

# blank line

