#!/bin/bash

#PBS -l nodes=1:ppn=1:gpus=1:k80,mem=20GB
#PBS -l other=compute_mode:default
#PBS -l walltime=10:00:00
#PBS -N 1GPU_asa32_avg
#PBS -j oe

module purge
module load theano/0.8.2 
module unload numpy/intel/1.10.1
module load mpi4py/openmpi/2.0.0
module unload cuda/7.0.28
module load pycuda/intel/2016.1.2
module load cudnn/7.0v4.0
module load pyzmq/intel/14.7.0

unset PBS_JOBID

cd /scratch/lt1410/MultiGPU/test

mpiexec -np 1 \
    sh /scratch/lt1410/MultiGPU/test/python-wrapper.sh

